<?php

function first_menu_menu_page() {
  return t("This is computer");
}

function first_menu_acer_menu_page() {
  return t("Acer company");
}

function first_menu_lenovo_menu_page() {
  return t("Lenovo company");
}

function first_menu_apple_menu_page() {
  return t("Apple company");
}

function first_menu_dell_menu_page() {
  return t("Dell company");
}

function first_menu_hp_menu_page() {
  return t("Hp company");
}

function first_menu_asus_menu_page() {
  return t("Usa");
}

function first_menu_usa_asus_menu_page() {
  return t("China");
}

