<?php
/**
 * Implements hook_menu().
 */
function first_menu_menu() {
  $items['admin/menu'] = [
    'title' => 'Computer',
    'description' => 'This is computer',
    'page callback' => 'first_menu_menu_page',
    'file' => 'first_menu.pages.inc',
    'expanded' => TRUE,
    'access callback' => TRUE,
  ];
  $items['admin/menu/acer'] = [
    'title' => 'Acer`s shops',
    'description' => 'Acer company',
    'page callback' => 'first_menu_acer_menu_page',
    'access callback' => TRUE,
    'file' => 'first_menu.pages.inc',
    'expanded' => TRUE,
  ];
  $items['admin/menu/lenovo'] = [
    'title' => 'Lenovo`s shops',
    'description' => 'Lenovo company',
    'page callback' => 'first_menu_lenovo_menu_page',
    'access callback' => TRUE,
    'file' => 'first_menu.pages.inc',
    'expanded' => TRUE,
  ];
  $items['admin/menu/apple'] = [
    'title' => 'Apple`s shops',
    'description' => 'Apple company',
    'page callback' => 'first_menu_apple_menu_page',
    'file' => 'first_menu.pages.inc',
    'access arguments' => array('access to menu'),
    'expanded' => TRUE,
  ];
  $items['admin/menu/dell'] = [
    'title' => 'Dell`s shops',
    'description' => 'Dell company',
    'page callback' => 'first_menu_dell_menu_page',
    'access callback' => TRUE,
    'file' => 'first_menu.pages.inc',
    'expanded' => TRUE,
  ];
  $items['admin/menu/hp'] = [
    'title' => 'Hp`s shops',
    'description' => 'Hp company',
    'page callback' => 'first_menu_hp_menu_page',
    'access callback' => TRUE,
    'file' => 'first_menu.pages.inc',
    'expanded' => TRUE,
  ];
  $items['admin/menu/asus'] = [
    'title' => 'Asus`s shops',
    'description' => 'Asus company',
    'page callback' => 'first_menu_asus_menu_page',
    'access callback' => TRUE,
    'file' => 'first_menu.pages.inc',
    'expanded' => TRUE,
  ];
  $items['admin/menu/asus/usa'] = [
    'title' => 'manufacturers country usa',
    'description' => 'Usa',
    'page callback' => 'first_menu_usa_asus_menu_page',
    'access callback' => TRUE,
    'file' => 'first_menu.pages.inc',
    'expanded' => TRUE,
  ];
  $items['admin/menu/asus/china'] = [
    'title' => 'manufacturers country china',
    'description' => 'China',
    'page callback' => 'first_menu_china_asus_menu_page',
    'access callback' => TRUE,
    'file' => 'first_menu.pages.inc',
    'expanded' => TRUE,
  ];
  $items['begin_item'] = [
    'title' => 'Begin Item',
    'description' => 'This is begin item',
    'page callback' => 'first_menu_begin_item_page',
    'file' => 'first_menu.pages.inc',
    'access callback' => TRUE,
    'expanded' => TRUE,
    ];

  return $items;
}
/**
 * Implements hook_permission().
 *
 */
function first_menu_permission() {
  return array(
    'access to menu' => array(
      'title' => t('Access to adding menu'),
      'description' => t('Administrator'),
    ),
  );
}

/**
 * @param $items
 */
/**
 * Implements hook_menu_alter().
 */
function first_menu_menu_alter(&$items)
{
    if (!empty($items['begin_item'])) {
        $items['begin_item_new'] = $items['begin_item'];
        $items['begin_item_new']['title'] = 'Altered item';
        unset($items['begin_item']);
    }
    if (!empty($items['begin_item_new'])) {
        $items['begin_item_new']['page callback'] = 'first_menu_begin_altered_page';
    }
    foreach ($items as $route => $item) {
        $result = module_invoke_all('first_menu_menu', $route, $item);
        drupal_alter('first_menu_menu', $result, $route, $item);
        foreach ($result as $subroute => $subitem) {
            $items[$route . '/' . $subroute] = $subitem;
        }
    }
}

/**
 * Implements hook_first_menu_menu().
 */
/**
 * Implements hook_first_menu_menu().
 */
function first_menu_first_menu_menu($route, $item)
{
    $subitems = array();
    if ($route == 'admin/menu/asus') {
        $subitems['country1'] = [
            'title' => 'Country 1',
            'description' => 'manufacturers country 1',
            'page callback' => 'first_menu_asus_menu_page',
            'access callback' => TRUE,
            'file' => 'first_menu.pages.inc',
            'expanded' => TRUE,
        ];
    }
    return $subitems;
}

